name: 'Wait for GHCR Container Image'
description: 'Wait for an image to be available in GitHub Container Registry'

inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  image-name:
    description: 'The image to wait on (e.g., "org/image-name:tag")'
    required: true
  timeout:
    description: 'Maximum time to wait in minutes'
    required: false
    default: '15'
  sleep-time:
    description: 'Time to wait between attempts in seconds'
    required: false
    default: '30'
  cache-image:
    description: 'Whether to keep the image cached locally after verification'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Login to GitHub Container Registry
      shell: bash
      run: echo "${{ inputs.github-token }}" | docker login ghcr.io -u ${{ inputs.github-username }} --password-stdin

    - name: Wait for Image
      shell: bash
      run: |
        echo "Waiting for image ghcr.io/${{ inputs.image-name }} to be available..."
        
        start_time=$(date +%s)
        timeout_seconds=$(( ${{ inputs.timeout }} * 60 ))
        
        while true; do
          # Use docker manifest inspect instead of pull for availability check
          if docker manifest inspect ghcr.io/${{ inputs.image-name }} >/dev/null 2>&1; then
            echo "Image is now available!"
            
            if [ "${{ inputs.cache-image }}" = "true" ]; then
              docker pull ghcr.io/${{ inputs.image-name }}
            fi
            
            exit 0
          fi
          
          current_time=$(date +%s)
          elapsed_time=$((current_time - start_time))
          
          if [ $elapsed_time -ge $timeout_seconds ]; then
            echo "Timeout reached after ${{ inputs.timeout }} minutes"
            exit 1
          fi
          
          echo "Image not yet available, waiting ${{ inputs.sleep-time }} seconds..."
          sleep ${{ inputs.sleep-time }}
        done